cors:
  origin-patterns: https://erudio.com.br,http://localhost:8080,http://localhost:3000
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  application:
    name: "spring-boot-with-erutio"
  datasource:
    url: jdbc:mysql://localhost:3309/rest_with_spring_erutio?useTimezone=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
    open-in-view: false
springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/api-docs-ui"
    operations-sorter: method